//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.08 at 08:43:38 PM PDT 
//


package org.webhop.ywdc.webservices.ups.ratingserviceselectionrequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RatingServiceSelectionRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RatingServiceSelectionRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Request" type="{}RequestType"/>
 *         &lt;element name="PickupType" type="{}PickupTypeType" minOccurs="0"/>
 *         &lt;element name="Shipment" type="{}ShipmentType"/>
 *         &lt;element name="CustomerClassification" type="{}CustomerClassificationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RatingServiceSelectionRequestType", propOrder = {
    "request",
    "pickupType",
    "shipment",
    "customerClassification"
})
public class RatingServiceSelectionRequestType {

    @XmlElement(name = "Request", required = true)
    protected RequestType request;
    @XmlElement(name = "PickupType")
    protected PickupTypeType pickupType;
    @XmlElement(name = "Shipment", required = true)
    protected ShipmentType shipment;
    @XmlElement(name = "CustomerClassification")
    protected CustomerClassificationType customerClassification;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link RequestType }
     *     
     */
    public RequestType getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestType }
     *     
     */
    public void setRequest(RequestType value) {
        this.request = value;
    }

    /**
     * Gets the value of the pickupType property.
     * 
     * @return
     *     possible object is
     *     {@link PickupTypeType }
     *     
     */
    public PickupTypeType getPickupType() {
        return pickupType;
    }

    /**
     * Sets the value of the pickupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PickupTypeType }
     *     
     */
    public void setPickupType(PickupTypeType value) {
        this.pickupType = value;
    }

    /**
     * Gets the value of the shipment property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentType }
     *     
     */
    public ShipmentType getShipment() {
        return shipment;
    }

    /**
     * Sets the value of the shipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentType }
     *     
     */
    public void setShipment(ShipmentType value) {
        this.shipment = value;
    }

    /**
     * Gets the value of the customerClassification property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerClassificationType }
     *     
     */
    public CustomerClassificationType getCustomerClassification() {
        return customerClassification;
    }

    /**
     * Sets the value of the customerClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerClassificationType }
     *     
     */
    public void setCustomerClassification(CustomerClassificationType value) {
        this.customerClassification = value;
    }

}
