//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.10 at 05:50:04 PM PDT 
//


package org.webhop.ywdc.webservices.ups.ratingserviceselectionresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NegotiatedRatesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NegotiatedRatesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NetSummaryCharges" type="{}NetSummaryChargesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NegotiatedRatesType", propOrder = {
    "netSummaryCharges"
})
public class NegotiatedRatesType {

    @XmlElement(name = "NetSummaryCharges")
    protected NetSummaryChargesType netSummaryCharges;

    /**
     * Gets the value of the netSummaryCharges property.
     * 
     * @return
     *     possible object is
     *     {@link NetSummaryChargesType }
     *     
     */
    public NetSummaryChargesType getNetSummaryCharges() {
        return netSummaryCharges;
    }

    /**
     * Sets the value of the netSummaryCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetSummaryChargesType }
     *     
     */
    public void setNetSummaryCharges(NetSummaryChargesType value) {
        this.netSummaryCharges = value;
    }

}
