//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.10 at 05:50:04 PM PDT 
//


package org.webhop.ywdc.webservices.ups.ratingserviceselectionresponse;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.webhop.ywdc.ratingserviceselectionresponse package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RatingServiceSelectionResponse_QNAME = new QName("", "RatingServiceSelectionResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.webhop.ywdc.ratingserviceselectionresponse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RatedShipmentBillingWeightType }
     * 
     */
    public RatedShipmentBillingWeightType createRatedShipmentBillingWeightType() {
        return new RatedShipmentBillingWeightType();
    }

    /**
     * Create an instance of {@link GrandTotalType }
     * 
     */
    public GrandTotalType createGrandTotalType() {
        return new GrandTotalType();
    }

    /**
     * Create an instance of {@link ErrorLocationType }
     * 
     */
    public ErrorLocationType createErrorLocationType() {
        return new ErrorLocationType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link TransportationChargesType }
     * 
     */
    public TransportationChargesType createTransportationChargesType() {
        return new TransportationChargesType();
    }

    /**
     * Create an instance of {@link TotalChargesType }
     * 
     */
    public TotalChargesType createTotalChargesType() {
        return new TotalChargesType();
    }

    /**
     * Create an instance of {@link ResponseType }
     * 
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link NetSummaryChargesType }
     * 
     */
    public NetSummaryChargesType createNetSummaryChargesType() {
        return new NetSummaryChargesType();
    }

    /**
     * Create an instance of {@link ServiceOptionsChargesType }
     * 
     */
    public ServiceOptionsChargesType createServiceOptionsChargesType() {
        return new ServiceOptionsChargesType();
    }

    /**
     * Create an instance of {@link RatedPackageType }
     * 
     */
    public RatedPackageType createRatedPackageType() {
        return new RatedPackageType();
    }

    /**
     * Create an instance of {@link NegotiatedRatesType }
     * 
     */
    public NegotiatedRatesType createNegotiatedRatesType() {
        return new NegotiatedRatesType();
    }

    /**
     * Create an instance of {@link RatedShipmentType }
     * 
     */
    public RatedShipmentType createRatedShipmentType() {
        return new RatedShipmentType();
    }

    /**
     * Create an instance of {@link RatingServiceSelectionResponseType }
     * 
     */
    public RatingServiceSelectionResponseType createRatingServiceSelectionResponseType() {
        return new RatingServiceSelectionResponseType();
    }

    /**
     * Create an instance of {@link UnitOfMeasurementType }
     * 
     */
    public UnitOfMeasurementType createUnitOfMeasurementType() {
        return new UnitOfMeasurementType();
    }

    /**
     * Create an instance of {@link BillingWeightType }
     * 
     */
    public BillingWeightType createBillingWeightType() {
        return new BillingWeightType();
    }

    /**
     * Create an instance of {@link TransactionReferenceType }
     * 
     */
    public TransactionReferenceType createTransactionReferenceType() {
        return new TransactionReferenceType();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RatingServiceSelectionResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RatingServiceSelectionResponse")
    public JAXBElement<RatingServiceSelectionResponseType> createRatingServiceSelectionResponse(RatingServiceSelectionResponseType value) {
        return new JAXBElement<RatingServiceSelectionResponseType>(_RatingServiceSelectionResponse_QNAME, RatingServiceSelectionResponseType.class, null, value);
    }

}
