//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.10 at 05:50:04 PM PDT 
//


package org.webhop.ywdc.webservices.ups.ratingserviceselectionresponse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RatedShipmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RatedShipmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Service" type="{}ServiceType"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RatedShipmentWarning" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillingWeight" type="{}RatedShipmentBillingWeightType"/>
 *         &lt;element name="TransportationCharges" type="{}TransportationChargesType"/>
 *         &lt;element name="ServiceOptionsCharges" type="{}ServiceOptionsChargesType" minOccurs="0"/>
 *         &lt;element name="TotalCharges" type="{}TotalChargesType"/>
 *         &lt;element name="GuaranteedDaysToDelivery" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ScheduleDeliveryTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RatedPackage" type="{}RatedPackageType" maxOccurs="200"/>
 *         &lt;element name="NegotiatedRates" type="{}NegotiatedRatesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RatedShipmentType", propOrder = {
    "service",
    "description",
    "ratedShipmentWarning",
    "billingWeight",
    "transportationCharges",
    "serviceOptionsCharges",
    "totalCharges",
    "guaranteedDaysToDelivery",
    "scheduleDeliveryTime",
    "ratedPackage",
    "negotiatedRates"
})
public class RatedShipmentType {

    @XmlElement(name = "Service", required = true)
    protected ServiceType service;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "RatedShipmentWarning")
    protected String ratedShipmentWarning;
    @XmlElement(name = "BillingWeight", required = true)
    protected RatedShipmentBillingWeightType billingWeight;
    @XmlElement(name = "TransportationCharges", required = true)
    protected TransportationChargesType transportationCharges;
    @XmlElement(name = "ServiceOptionsCharges")
    protected ServiceOptionsChargesType serviceOptionsCharges;
    @XmlElement(name = "TotalCharges", required = true)
    protected TotalChargesType totalCharges;
    @XmlElement(name = "GuaranteedDaysToDelivery", required = true)
    protected String guaranteedDaysToDelivery;
    @XmlElement(name = "ScheduleDeliveryTime", required = true)
    protected String scheduleDeliveryTime;
    @XmlElement(name = "RatedPackage", required = true)
    protected List<RatedPackageType> ratedPackage;
    @XmlElement(name = "NegotiatedRates")
    protected NegotiatedRatesType negotiatedRates;

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceType }
     *     
     */
    public ServiceType getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceType }
     *     
     */
    public void setService(ServiceType value) {
        this.service = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the ratedShipmentWarning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatedShipmentWarning() {
        return ratedShipmentWarning;
    }

    /**
     * Sets the value of the ratedShipmentWarning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatedShipmentWarning(String value) {
        this.ratedShipmentWarning = value;
    }

    /**
     * Gets the value of the billingWeight property.
     * 
     * @return
     *     possible object is
     *     {@link RatedShipmentBillingWeightType }
     *     
     */
    public RatedShipmentBillingWeightType getBillingWeight() {
        return billingWeight;
    }

    /**
     * Sets the value of the billingWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatedShipmentBillingWeightType }
     *     
     */
    public void setBillingWeight(RatedShipmentBillingWeightType value) {
        this.billingWeight = value;
    }

    /**
     * Gets the value of the transportationCharges property.
     * 
     * @return
     *     possible object is
     *     {@link TransportationChargesType }
     *     
     */
    public TransportationChargesType getTransportationCharges() {
        return transportationCharges;
    }

    /**
     * Sets the value of the transportationCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportationChargesType }
     *     
     */
    public void setTransportationCharges(TransportationChargesType value) {
        this.transportationCharges = value;
    }

    /**
     * Gets the value of the serviceOptionsCharges property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceOptionsChargesType }
     *     
     */
    public ServiceOptionsChargesType getServiceOptionsCharges() {
        return serviceOptionsCharges;
    }

    /**
     * Sets the value of the serviceOptionsCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceOptionsChargesType }
     *     
     */
    public void setServiceOptionsCharges(ServiceOptionsChargesType value) {
        this.serviceOptionsCharges = value;
    }

    /**
     * Gets the value of the totalCharges property.
     * 
     * @return
     *     possible object is
     *     {@link TotalChargesType }
     *     
     */
    public TotalChargesType getTotalCharges() {
        return totalCharges;
    }

    /**
     * Sets the value of the totalCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalChargesType }
     *     
     */
    public void setTotalCharges(TotalChargesType value) {
        this.totalCharges = value;
    }

    /**
     * Gets the value of the guaranteedDaysToDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuaranteedDaysToDelivery() {
        return guaranteedDaysToDelivery;
    }

    /**
     * Sets the value of the guaranteedDaysToDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuaranteedDaysToDelivery(String value) {
        this.guaranteedDaysToDelivery = value;
    }

    /**
     * Gets the value of the scheduleDeliveryTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduleDeliveryTime() {
        return scheduleDeliveryTime;
    }

    /**
     * Sets the value of the scheduleDeliveryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduleDeliveryTime(String value) {
        this.scheduleDeliveryTime = value;
    }

    /**
     * Gets the value of the ratedPackage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ratedPackage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRatedPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RatedPackageType }
     * 
     * 
     */
    public List<RatedPackageType> getRatedPackage() {
        if (ratedPackage == null) {
            ratedPackage = new ArrayList<RatedPackageType>();
        }
        return this.ratedPackage;
    }

    /**
     * Gets the value of the negotiatedRates property.
     * 
     * @return
     *     possible object is
     *     {@link NegotiatedRatesType }
     *     
     */
    public NegotiatedRatesType getNegotiatedRates() {
        return negotiatedRates;
    }

    /**
     * Sets the value of the negotiatedRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link NegotiatedRatesType }
     *     
     */
    public void setNegotiatedRates(NegotiatedRatesType value) {
        this.negotiatedRates = value;
    }

}
